name: AWS - EKS

on:
  push:
    branches:
      - main
    paths:
      - 'eks/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - refresh
          - destroy
  workflow_call:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: string
        default: 'plan'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-2
  TOFU_VERSION: 1.8.5
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  TF_STATE_KEY: eks/terraform.tfstate
  TF_LOCK_TABLE: ${{ secrets.TF_LOCK_TABLE }}

jobs:
  deploy:
    name: Deploy EKS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Annotate Workflow Run Details
        run: |
          ACTION="${{ inputs.action || 'push' }}"
          echo "::notice title=Workflow Action::Action: $ACTION, Branch: ${{ github.ref_name }}"
          echo "::notice title=Workflow Start Time::Started: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          echo "::notice title=Commit SHA::Commit: ${{ github.sha }}"
          echo "::notice title=OpenTofu Version::OpenTofu Version: ${{ env.TOFU_VERSION }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}
      - name: Cache OpenTofu Providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tofu-${{ env.TOFU_VERSION }}-providers-${{ hashFiles('eks/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-tofu-${{ env.TOFU_VERSION }}-providers-
      - name: OpenTofu Init
        run: |
          export TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache
          tofu init -backend-config="bucket=$TF_STATE_BUCKET" \
                    -backend-config="key=$TF_STATE_KEY" \
                    -backend-config="region=$AWS_REGION" \
                    -backend-config="dynamodb_table=$TF_LOCK_TABLE"
      - name: OpenTofu Validate
        run: tofu validate
      - name: OpenTofu Plan
        id: plan
        if: github.event_name == 'push' || inputs.action == 'plan' || inputs.action == 'apply'
        run: |
          tofu plan -out=tfplan -no-color
          echo "Plan generated at tfplan"
      - name: OpenTofu Apply
        if: (github.event_name == 'push' || inputs.action == 'apply') && steps.plan.outcome == 'success'
        run: tofu apply -no-color -auto-approve tfplan > /dev/null 2>&1
      - name: OpenTofu Refresh
        if: inputs.action == 'refresh'
        run: tofu refresh -no-color > /dev/null 2>&1
      - name: OpenTofu Destroy
        if: inputs.action == 'destroy'
        run: tofu destroy -no-color -auto-approve > /dev/null 2>&1
      - name: Cleanup
        if: always() && (github.event_name == 'push' || inputs.action == 'plan' || inputs.action == 'apply')
        run: rm -f tfplan