name: Destroy All AWS Environment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DESTROY" to confirm environment destruction'
        required: true
        default: ''
        type: string

permissions:
  contents: read
  id-token: write

concurrency:
  group: destroy-all-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-confirmation:
    runs-on: ubuntu-latest
    steps:
      - name: Check Confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DESTROY" ]; then
            echo "Confirmation must be 'DESTROY'. Aborting."
            exit 1
          fi
          echo "Confirmation valid. Proceeding with destruction."

  destroy-analytics:
    needs: validate-confirmation
    uses: ./.github/workflows/analytics-deploy.yml
    with:
      action: destroy
    secrets: inherit

  destroy-eks:
    needs: validate-confirmation
    uses: ./.github/workflows/eks-deploy.yml
    with:
      action: destroy
    secrets: inherit

  destroy-ec2-jump-box:
    needs:
      - destroy-analytics
      - destroy-eks
    uses: ./.github/workflows/ec2-jump-box-deploy.yml
    with:
      action: destroy
    secrets: inherit

  destroy-vpc:
    needs: destroy-ec2-jump-box
    uses: ./.github/workflows/vpc-deploy.yml
    with:
      action: destroy
    secrets: inherit