name: Deploy IAM to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'iam/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - refresh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-2
  TOFU_VERSION: 1.8.5
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  TF_STATE_KEY: iam/terraform.tfstate
  TF_LOCK_TABLE: ${{ secrets.TF_LOCK_TABLE }}

jobs:
  deploy:
    name: Deploy IAM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iam

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Announce Selected Action
        run: |
          ACTION="${{ github.event.inputs.action || 'push' }}"
          echo "Selected action: $ACTION on branch ${{ github.ref_name }}"
          echo "::notice title=Workflow Action::Running $ACTION on ${{ github.ref_name }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: Cache OpenTofu Providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tofu-${{ env.TOFU_VERSION }}-providers-${{ hashFiles('iam/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-tofu-${{ env.TOFU_VERSION }}-providers-

      - name: OpenTofu Init
        run: |
          export TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache
          tofu init -backend-config="bucket=$TF_STATE_BUCKET" \
                    -backend-config="key=$TF_STATE_KEY" \
                    -backend-config="region=$AWS_REGION" \
                    -backend-config="dynamodb_table=$TF_LOCK_TABLE"

      - name: OpenTofu Validate
        run: tofu validate

      - name: OpenTofu Plan
        id: plan
        if: github.event.inputs.action == 'plan' || github.event_name == 'push'
        run: |
          tofu plan -out=tfplan -no-color
          echo "Plan generated at tfplan"

      - name: OpenTofu Apply
        if: |
          (github.event_name == 'push' || 
           (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')) &&
          steps.plan.outcome == 'success'
        run: tofu apply -no-color -auto-approve tfplan

      - name: OpenTofu Refresh
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'refresh'
        run: tofu refresh -no-color

      - name: Cleanup
        if: always() && (github.event.inputs.action != 'refresh')
        run: rm -f tfplan