name: Set Up AWS Environment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DEPLOY" to confirm environment deployment'
        required: true
        default: ''
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  confirm-deploy:
    name: Confirm Environment Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Verify Deploy Confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DEPLOY" ]; then
            echo "Confirmation must be 'DEPLOY'. Aborting."
            exit 1
          fi
          echo "Confirmation valid. Proceeding with deployment."
  vpc-apply:
    name: Apply VPC
    needs: confirm-deploy
    uses: ./.github/workflows/vpc-lifecycle.yml
    with:
      action: apply
    secrets: inherit
  jump-box-apply:
    name: Apply Jump Box
    needs: vpc-apply
    uses: ./.github/workflows/jump-box-lifecycle.yml
    with:
      action: apply
    secrets: inherit
  eks-apply:
    name: Apply EKS
    needs: vpc-apply
    uses: ./.github/workflows/eks-lifecycle.yml
    with:
      action: apply
    secrets: inherit