name: Tear Down AWS Environment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DESTROY" to confirm environment destruction'
        required: true
        default: ''
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  validate-confirmation:
    runs-on: ubuntu-latest
    steps:
      - name: Check Confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DESTROY" ]; then
            echo "Confirmation must be 'DESTROY'. Aborting."
            exit 1
          fi
          echo "Confirmation valid. Proceeding with destruction."
  destroy-analytics:
    needs: validate-confirmation
    uses: ./.github/workflows/analytics-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  destroy-eks:
    needs: validate-confirmation
    uses: ./.github/workflows/eks-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  destroy-jump-box:
    needs: validate-confirmation
    uses: ./.github/workflows/jump-box-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  destroy-vpc:
    needs:
      - destroy-analytics
      - destroy-eks
      - destroy-jump-box
    uses: ./.github/workflows/vpc-lifecycle.yml
    with:
      action: destroy
    secrets: inherit