name: Tear Down AWS Environment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DESTROY" to confirm environment destruction'
        required: true
        default: ''
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  confirm-destroy:
    name: Confirm Environment Destruction
    runs-on: ubuntu-latest
    steps:
      - name: Verify Destroy Confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DESTROY" ]; then
            echo "Confirmation must be 'DESTROY'. Aborting."
            exit 1
          fi
          echo "Confirmation valid. Proceeding with destruction."
  analytics-destroy:
    name: Destroy Analytics
    needs: confirm-destroy
    uses: ./.github/workflows/analytics-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  eks-destroy:
    name: Destroy EKS
    needs: confirm-destroy
    uses: ./.github/workflows/eks-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  jump-box-destroy:
    name: Destroy Jump Box
    needs: confirm-destroy
    uses: ./.github/workflows/jump-box-lifecycle.yml
    with:
      action: destroy
    secrets: inherit
  vpc-destroy:
    name: Destroy VPC
    needs:
      - analytics-destroy
      - eks-destroy
      - jump-box-destroy
    uses: ./.github/workflows/vpc-lifecycle.yml
    with:
      action: destroy
    secrets: inherit